server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE 
    username: sa
    #password:  
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
  application:
    name: item-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/