server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE 
    username: sa
    #password:  
    driver-class-name: org.h2.Driver
  cloud:
    config:
      uri: http://localhost:8089
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
  application:
    name: item-service